# Generated by Django 3.1.1 on 2020-10-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='profile_images'),
        ),
    ]
