# Generated by Django 3.1.1 on 2020-10-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20201004_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=255, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
