# Generated by Django 3.1.1 on 2020-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_auto_20201012_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
