# Generated by Django 3.1.1 on 2020-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_auto_20201012_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profiles/<django.db.models.fields.CharField>'),
        ),
    ]
