# Generated by Django 3.1.1 on 2020-10-12 18:49

import Login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_auto_20201012_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to=Login.models.user_directory_path),
        ),
    ]
