# Generated by Django 3.1.1 on 2020-10-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_auto_20201012_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
